[package]
name = "tsgo-client"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
serde = { version = "1", features = [ "derive" ] }
cbor4ii = {version = "1", features = ["serde1"]}
serde_bytes = "0.11.19"
bitflags = { version = "2.10"}